apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
  namespace: default
  labels:
      app.kubernetes.io/name: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scaletestapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scaletestapp
    spec:
      enableServiceLinks: false
      containers:
      - name: scaletestapp
        image: shestera/scaletestapp
        resources:
         requests:
           memory: "10Mi"
         limits:
           memory: "30Mi"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
  strategy:
    type: RollingUpdate
