apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
spec:
  selector:
    app.kubernetes.io/name: scaletestapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: http
      nodePort: 30007
